### ISSUE TITLE
False positive no space after "]"

### ISSUE THREAD

**Issue by yguedidi** [friendsoftwig/twigcs#65] opened 2019-05-24 14:35 UTC
The following code gives a false positive:

```twig
{% for data in items[foo.id] if data.bar is not null %}
```

The error: `ERROR There should be no space after "]".`

**Comment by OwlyCode** [comment] 2019-05-29 15:45
Hello, thanks for reporting this! This is a duplicate of https://github.com/allocine/twigcs/issues/56 so I will close this one and track it from #56.

**Closed as completed by OwlyCode** 2019-05-29 15:45 UTC
Labels: bug
